## **Identifying Treatments with More Than Four Cuts per Year in the CEROM Agricultural Experiment**

In [1]:
# Import the necessary libraries
import numpy as np
import pandas as pd

In [5]:
# Import the yield dataset
data = pd.read_excel('../data/interim/05_CEROM_Yield_With_Flooding_Related_Columns_2008-24.xlsx', sheet_name='Sheet1')

In [7]:
# Display the first few rows of the dataset
data.head()

,Year,Block,In_swale_or_not,Soil_drainage,Soil_drainage_level,Plot,Rotation,Treatment,Culture,Rotation_type,...,Protein_adjusted,Oil_adjusted,Lodging,Specific_weight,Humidity,Humidity_from,PMG,PCG,Residue,Comments2
0,2008,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,NaN
1,2008,1,Not in swale,Best,5,105,R2,D.R2.M.I,Maize,Annual,...,8.970506,3.884252,NaN,68.72,22.1,Grains at harvest,NaN,NaN,17884.0,NaN
2,2008,1,Not in swale,Best,5,107,R2,D.R2.M.E,Maize,Annual,...,9.664563,4.350714,NaN,68.67,22.4,Grains at harvest,NaN,NaN,19058.0,NaN
3,2008,1,Not in swale,Bad,3,111,R1,D.R1.M.E,Maize,Annual,...,9.130194,4.254848,NaN,69.81,22.3,Grains at harvest,NaN,NaN,19238.0,NaN
4,2008,1,Not in swale,Bad,3,114,R1,D.R1.M.I,Maize,Annual,...,9.432082,4.406067,NaN,69.37,22.3,Grains at harvest,NaN,NaN,18974.0,NaN

In [8]:
# Get the list of unique treatments in the dataset
treatments_list = data['Treatment'].value_counts().reset_index()['Treatment'].to_list()

In [10]:
# Display the list of unique treatments
treatments_list

['X.R4.M.E',
 'D.R2.M.I',
 'D.R2.M.E',
 'D.R1.M.E',
 'D.R1.M.I',
 'D.R3.M.E',
 'D.R3.M.I',
 'L.R2.M.I',
 'L.R2.M.E',
 'L.R3.M.I',
 'L.R3.M.E',
 'L.R1.M.E',
 'L.R1.M.I']

In [16]:
# Loop through each treatment and count the number of cuts for each year from 2008 to 2024
for i in treatments_list:
  print('Treatment:',i)
  for j in range(2008,2025):
    print(data[data['Treatment'] == i][data[data['Treatment'] == i]['Year'] == j].shape[0],'number of cuts','for the year',j)

Treatment: X.R4.M.E
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
8 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
16 number of cuts for the year 2021
12 number of cuts for the year 2022
12 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: D.R2.M.I
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: D.R2.M.E
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: D.R1.M.E
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: D.R1.M.I
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: D.R3.M.E
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: D.R3.M.I
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: L.R2.M.I
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: L.R2.M.E
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: L.R3.M.I
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: L.R3.M.E
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: L.R1.M.E
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024
Treatment: L.R1.M.I
4 number of cuts for the year 2008
4 number of cuts for the year 2009
4 number of cuts for the year 2010
4 number of cuts for the year 2011
4 number of cuts for the year 2012
4 number of cuts for the year 2013
4 number of cuts for the year 2014
4 number of cuts for the year 2015
4 number of cuts for the year 2016
4 number of cuts for the year 2017
4 number of cuts for the year 2018
4 number of cuts for the year 2019
4 number of cuts for the year 2020
4 number of cuts for the year 2021
4 number of cuts for the year 2022
4 number of cuts for the year 2023
4 number of cuts for the year 2024

In [18]:
# Display the rows for a X.R4.M.E treatment
data_XR4ME = data[data['Treatment'] == 'X.R4.M.E']

In [19]:
# Display the rows for a X.R4.M.E treatment
data_XR4ME

,Year,Block,In_swale_or_not,Soil_drainage,Soil_drainage_level,Plot,Rotation,Treatment,Culture,Rotation_type,...,Protein_adjusted,Oil_adjusted,Lodging,Specific_weight,Humidity,Humidity_from,PMG,PCG,Residue,Comments2
0,2008,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,NaN
25,2008,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,NaN
32,2008,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,NaN
39,2008,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,NaN
52,2009,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,Avec légumineuses
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,2023,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,79.227334,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
864,2024,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,Sursemis de graminées
889,2024,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,Sursemis de graminées
896,2024,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,Sursemis de graminées
903,2024,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,NaN,Forage moisture at harvest,NaN,NaN,NaN,Sursemis de graminées

In [20]:
# Display the rows for X.R4.M.E treatment for the years 2021 to 2023 which have more than 4 cuts in a year
data_XR4ME_2021_to_2023 = data_XR4ME[(data_XR4ME['Year'] >= 2021) & (data_XR4ME['Year'] <= 2023)]

In [22]:
# Display the rows for X.R4.M.E treatment for the years 2021 to 2023
data_XR4ME_2021_to_2023

,Year,Block,In_swale_or_not,Soil_drainage,Soil_drainage_level,Plot,Rotation,Treatment,Culture,Rotation_type,...,Protein_adjusted,Oil_adjusted,Lodging,Specific_weight,Humidity,Humidity_from,PMG,PCG,Residue,Comments2
680,2021,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,69.780220,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
681,2021,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,76.914661,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
682,2021,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,80.131004,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
683,2021,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,78.049308,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
708,2021,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,69.104803,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
709,2021,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,75.000000,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
710,2021,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,83.114035,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
711,2021,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,76.635514,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
718,2021,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,70.394737,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
719,2021,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,77.391304,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
720,2021,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,81.896552,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
721,2021,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,79.059829,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
728,2021,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,68.017525,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
729,2021,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,75.974026,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
730,2021,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,81.222707,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
731,2021,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,78.378378,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
744,2022,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,83.484646,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
745,2022,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,81.056966,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
746,2022,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,80.104782,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
771,2022,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,82.594142,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
772,2022,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,80.721221,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
773,2022,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,81.696609,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
780,2022,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,81.930447,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
781,2022,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,81.780250,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
782,2022,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,80.839048,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
789,2022,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,81.480000,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
790,2022,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,82.310984,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
791,2022,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,80.497925,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
804,2023,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,73.011260,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
805,2023,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,84.142488,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
806,2023,1,Not in swale,Best,5,101,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,79.265449,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
831,2023,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,73.559078,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
832,2023,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,83.778173,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
833,2023,2,In swale,Best,5,239,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,79.016903,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
840,2023,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,74.207976,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
841,2023,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,83.137255,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
842,2023,3,Not in swale,Best,5,320,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,77.877597,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
849,2023,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,72.851346,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
850,2023,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,83.976732,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure
851,2023,4,Not in swale,Best,5,403,R4,X.R4.M.E,Prairie,Permanent,...,NaN,NaN,NaN,NaN,79.227334,Forage moisture at harvest,NaN,NaN,NaN,Luzernière pure

# **Conclusion** - Treatment X.R4.M.E has more than 4 cuts per year for the years 2021 to 2023 meaning that the crop was harvested not in a single go but many times in that year